title: "Rasoul Norouzi"
author: "Rasoul Norouzi"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: Home}
  - {file: "cv.md", title: CV}
#   - {file: "blog.md", title: Blog}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Skype, icon: skype, url: "https://join.skype.com/invite/mW7xxTxkv1T8"}
  - {title: Mail, icon: envelope, url: "rslnorouzi@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/SindbadBahri"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/rasoulnorouzi"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
